CREATE TABLE SHIPS
(SHIP_ID NUMBER,
SHIP_NAME VARCHAR2(20),
CAPACITY NUMBER,
LENGTH NUMBER);

INSERT INTO SHIPS (SHIP_ID, SHIP_NAME, CAPACITY, LENGTH)
VALUES (1, 'Codd Crystal', 2052, 855);

SELECT SHIP_NAME CAPACITY, LENGTH
FROM SHIPS;